### ISSUE TITLE
[Tracking] todo list for field

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/field#11]
To do 
- [ ] to do item
- [x] to do item
- [x] to do item
- [ ] to do item

**Comment by mstuart1** [comment]
changed anem_id from 486 to 488 because type-o, verified on data sheet
